//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace weatherAssistant.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("weatherAssistant.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check.
        /// </summary>
        public static string Check {
            get {
                return ResourceManager.GetString("Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloudiness.
        /// </summary>
        public static string Cloudiness {
            get {
                return ResourceManager.GetString("Cloudiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition.
        /// </summary>
        public static string Condition {
            get {
                return ResourceManager.GetString("Condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinate.
        /// </summary>
        public static string Coordinate {
            get {
                return ResourceManager.GetString("Coordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination City.
        /// </summary>
        public static string DestinationCity {
            get {
                return ResourceManager.GetString("DestinationCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details_word {
            get {
                return ResourceManager.GetString("Details_word", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction.
        /// </summary>
        public static string Direction {
            get {
                return ResourceManager.GetString("Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to East.
        /// </summary>
        public static string Direction_East {
            get {
                return ResourceManager.GetString("Direction_East", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North.
        /// </summary>
        public static string Direction_North {
            get {
                return ResourceManager.GetString("Direction_North", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North-East.
        /// </summary>
        public static string Direction_NorthEast {
            get {
                return ResourceManager.GetString("Direction_NorthEast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North-West.
        /// </summary>
        public static string Direction_NorthWest {
            get {
                return ResourceManager.GetString("Direction_NorthWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South.
        /// </summary>
        public static string Direction_South {
            get {
                return ResourceManager.GetString("Direction_South", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South-East.
        /// </summary>
        public static string Direction_SouthEast {
            get {
                return ResourceManager.GetString("Direction_SouthEast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South-West.
        /// </summary>
        public static string Direction_SouthWest {
            get {
                return ResourceManager.GetString("Direction_SouthWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to West.
        /// </summary>
        public static string Direction_West {
            get {
                return ResourceManager.GetString("Direction_West", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frost.
        /// </summary>
        public static string Frost {
            get {
                return ResourceManager.GetString("Frost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heat.
        /// </summary>
        public static string Heat {
            get {
                return ResourceManager.GetString("Heat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hour.
        /// </summary>
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humidity.
        /// </summary>
        public static string Humidity {
            get {
                return ResourceManager.GetString("Humidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map of Europe.
        /// </summary>
        public static string MapOfEurope {
            get {
                return ResourceManager.GetString("MapOfEurope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map of Europe (animated).
        /// </summary>
        public static string MapOfEurope_animated {
            get {
                return ResourceManager.GetString("MapOfEurope_animated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map of Poland.
        /// </summary>
        public static string MapOfPoland {
            get {
                return ResourceManager.GetString("MapOfPoland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map of Poland (animated).
        /// </summary>
        public static string MapOfPoland_animated {
            get {
                return ResourceManager.GetString("MapOfPoland_animated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string Menu_Notifications {
            get {
                return ResourceManager.GetString("Menu_Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan a trip.
        /// </summary>
        public static string Menu_PlanTheTrip {
            get {
                return ResourceManager.GetString("Menu_PlanTheTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storm Search.
        /// </summary>
        public static string Menu_StormSearch {
            get {
                return ResourceManager.GetString("Menu_StormSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stormy Map.
        /// </summary>
        public static string Menu_StormyMap {
            get {
                return ResourceManager.GetString("Menu_StormyMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather Forecast.
        /// </summary>
        public static string Menu_WeatherForecast {
            get {
                return ResourceManager.GetString("Menu_WeatherForecast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nearest thunderbolt.
        /// </summary>
        public static string NearestThunderbolt {
            get {
                return ResourceManager.GetString("NearestThunderbolt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Notifications_Cancel {
            get {
                return ResourceManager.GetString("Notifications_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Notifications_Confirm {
            get {
                return ResourceManager.GetString("Notifications_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storm notifications.
        /// </summary>
        public static string Notifications_StormNotifications {
            get {
                return ResourceManager.GetString("Notifications_StormNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency of updates.
        /// </summary>
        public static string Notifications_UpdatesFrequency {
            get {
                return ResourceManager.GetString("Notifications_UpdatesFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather alert notifications.
        /// </summary>
        public static string Notifications_WeatherAlertNotifications {
            get {
                return ResourceManager.GetString("Notifications_WeatherAlertNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of thunderbolts.
        /// </summary>
        public static string NumberOfThunderbolts {
            get {
                return ResourceManager.GetString("NumberOfThunderbolts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        public static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frost, 1st degree warning.
        /// </summary>
        public static string PlanTheTrip_Risk_Frost_Degree1 {
            get {
                return ResourceManager.GetString("PlanTheTrip_Risk_Frost_Degree1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frost, 2st degree warning.
        /// </summary>
        public static string PlanTheTrip_Risk_Frost_Degree2 {
            get {
                return ResourceManager.GetString("PlanTheTrip_Risk_Frost_Degree2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frost, 3st degree warning.
        /// </summary>
        public static string PlanTheTrip_Risk_Frost_Degree3 {
            get {
                return ResourceManager.GetString("PlanTheTrip_Risk_Frost_Degree3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heat, 1st degree warning.
        /// </summary>
        public static string PlanTheTrip_Risk_Heat_Degree1 {
            get {
                return ResourceManager.GetString("PlanTheTrip_Risk_Heat_Degree1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heat, 2st degree warning.
        /// </summary>
        public static string PlanTheTrip_Risk_Heat_Degree2 {
            get {
                return ResourceManager.GetString("PlanTheTrip_Risk_Heat_Degree2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heat, 3st degree warning.
        /// </summary>
        public static string PlanTheTrip_Risk_Heat_Degree3 {
            get {
                return ResourceManager.GetString("PlanTheTrip_Risk_Heat_Degree3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Risk.
        /// </summary>
        public static string PlanTheTrip_Risk_High {
            get {
                return ResourceManager.GetString("PlanTheTrip_Risk_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High cloudiness.
        /// </summary>
        public static string PlanTheTrip_Risk_High_Cloudiness {
            get {
                return ResourceManager.GetString("PlanTheTrip_Risk_High_Cloudiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lightning detected in the area.
        /// </summary>
        public static string PlanTheTrip_Risk_High_Storms {
            get {
                return ResourceManager.GetString("PlanTheTrip_Risk_High_Storms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature above the norm.
        /// </summary>
        public static string PlanTheTrip_Risk_High_Temperature {
            get {
                return ResourceManager.GetString("PlanTheTrip_Risk_High_Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poor visibility.
        /// </summary>
        public static string PlanTheTrip_Risk_High_Visibility {
            get {
                return ResourceManager.GetString("PlanTheTrip_Risk_High_Visibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strong wind.
        /// </summary>
        public static string PlanTheTrip_Risk_High_Wind {
            get {
                return ResourceManager.GetString("PlanTheTrip_Risk_High_Wind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderate Risk.
        /// </summary>
        public static string PlanTheTrip_Risk_Moderate {
            get {
                return ResourceManager.GetString("PlanTheTrip_Risk_Moderate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderate cloudiness.
        /// </summary>
        public static string PlanTheTrip_Risk_Moderate_Cloudiness {
            get {
                return ResourceManager.GetString("PlanTheTrip_Risk_Moderate_Cloudiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature within normal limits.
        /// </summary>
        public static string PlanTheTrip_Risk_Moderate_Temperature {
            get {
                return ResourceManager.GetString("PlanTheTrip_Risk_Moderate_Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderate visibility.
        /// </summary>
        public static string PlanTheTrip_Risk_Moderate_Visibility {
            get {
                return ResourceManager.GetString("PlanTheTrip_Risk_Moderate_Visibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderate wind.
        /// </summary>
        public static string PlanTheTrip_Risk_Moderate_Wind {
            get {
                return ResourceManager.GetString("PlanTheTrip_Risk_Moderate_Wind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Risk.
        /// </summary>
        public static string PlanTheTrip_Risk_None {
            get {
                return ResourceManager.GetString("PlanTheTrip_Risk_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low cloudiness.
        /// </summary>
        public static string PlanTheTrip_Risk_None_Cloudiness {
            get {
                return ResourceManager.GetString("PlanTheTrip_Risk_None_Cloudiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No lightning in the area.
        /// </summary>
        public static string PlanTheTrip_Risk_None_Storms {
            get {
                return ResourceManager.GetString("PlanTheTrip_Risk_None_Storms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature in the norm.
        /// </summary>
        public static string PlanTheTrip_Risk_None_Temperature {
            get {
                return ResourceManager.GetString("PlanTheTrip_Risk_None_Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good visibility.
        /// </summary>
        public static string PlanTheTrip_Risk_None_Visibility {
            get {
                return ResourceManager.GetString("PlanTheTrip_Risk_None_Visibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No weather warnings in the area.
        /// </summary>
        public static string PlanTheTrip_Risk_None_Warnings {
            get {
                return ResourceManager.GetString("PlanTheTrip_Risk_None_Warnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weak wind.
        /// </summary>
        public static string PlanTheTrip_Risk_None_Wind {
            get {
                return ResourceManager.GetString("PlanTheTrip_Risk_None_Wind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rain, 1st degree warning.
        /// </summary>
        public static string PlanTheTrip_Risk_Rain_Degree1 {
            get {
                return ResourceManager.GetString("PlanTheTrip_Risk_Rain_Degree1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rain, 2st degree warning.
        /// </summary>
        public static string PlanTheTrip_Risk_Rain_Degree2 {
            get {
                return ResourceManager.GetString("PlanTheTrip_Risk_Rain_Degree2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rain, 3st degree warning.
        /// </summary>
        public static string PlanTheTrip_Risk_Rain_Degree3 {
            get {
                return ResourceManager.GetString("PlanTheTrip_Risk_Rain_Degree3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thunderstorms, 1st degree warning.
        /// </summary>
        public static string PlanTheTrip_Risk_Storms_Degree1 {
            get {
                return ResourceManager.GetString("PlanTheTrip_Risk_Storms_Degree1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thunderstorms, 2st degree warning.
        /// </summary>
        public static string PlanTheTrip_Risk_Storms_Degree2 {
            get {
                return ResourceManager.GetString("PlanTheTrip_Risk_Storms_Degree2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thunderstorms, 3st degree warning.
        /// </summary>
        public static string PlanTheTrip_Risk_Storms_Degree3 {
            get {
                return ResourceManager.GetString("PlanTheTrip_Risk_Storms_Degree3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tornado, 1st degree warning.
        /// </summary>
        public static string PlanTheTrip_Risk_Tornado_Degree1 {
            get {
                return ResourceManager.GetString("PlanTheTrip_Risk_Tornado_Degree1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tornado, 2st degree warning.
        /// </summary>
        public static string PlanTheTrip_Risk_Tornado_Degree2 {
            get {
                return ResourceManager.GetString("PlanTheTrip_Risk_Tornado_Degree2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tornado, 3st degree warning.
        /// </summary>
        public static string PlanTheTrip_Risk_Tornado_Degree3 {
            get {
                return ResourceManager.GetString("PlanTheTrip_Risk_Tornado_Degree3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind, 1st degree warning.
        /// </summary>
        public static string PlanTheTrip_Risk_Wind_Degree1 {
            get {
                return ResourceManager.GetString("PlanTheTrip_Risk_Wind_Degree1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind, 2st degree warning.
        /// </summary>
        public static string PlanTheTrip_Risk_Wind_Degree2 {
            get {
                return ResourceManager.GetString("PlanTheTrip_Risk_Wind_Degree2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind, 3st degree warning.
        /// </summary>
        public static string PlanTheTrip_Risk_Wind_Degree3 {
            get {
                return ResourceManager.GetString("PlanTheTrip_Risk_Wind_Degree3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressure.
        /// </summary>
        public static string Pressure {
            get {
                return ResourceManager.GetString("Pressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radius.
        /// </summary>
        public static string Radius {
            get {
                return ResourceManager.GetString("Radius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rain.
        /// </summary>
        public static string Rain {
            get {
                return ResourceManager.GetString("Rain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source City.
        /// </summary>
        public static string SourceCity {
            get {
                return ResourceManager.GetString("SourceCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sources.
        /// </summary>
        public static string Sources {
            get {
                return ResourceManager.GetString("Sources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        public static string Speed {
            get {
                return ResourceManager.GetString("Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storms.
        /// </summary>
        public static string Storms {
            get {
                return ResourceManager.GetString("Storms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunrise.
        /// </summary>
        public static string Sunrise {
            get {
                return ResourceManager.GetString("Sunrise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunset.
        /// </summary>
        public static string Sunset {
            get {
                return ResourceManager.GetString("Sunset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Title_test {
            get {
                return ResourceManager.GetString("Title_test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tornado.
        /// </summary>
        public static string Tornado {
            get {
                return ResourceManager.GetString("Tornado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From -20 to -25 °C.
        /// </summary>
        public static string Warning_Frost1 {
            get {
                return ResourceManager.GetString("Warning_Frost1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From -26 to -30 °C.
        /// </summary>
        public static string Warning_Frost2 {
            get {
                return ResourceManager.GetString("Warning_Frost2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Below -30 °C.
        /// </summary>
        public static string Warning_Frost3 {
            get {
                return ResourceManager.GetString("Warning_Frost3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From 30 to 34 °C.
        /// </summary>
        public static string Warning_Heat1 {
            get {
                return ResourceManager.GetString("Warning_Heat1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From 35 to 38 °C.
        /// </summary>
        public static string Warning_Heat2 {
            get {
                return ResourceManager.GetString("Warning_Heat2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Above 38 °C.
        /// </summary>
        public static string Warning_Heat3 {
            get {
                return ResourceManager.GetString("Warning_Heat3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rain from 25 to 40 mm
        ///in 24 hours
        ///or
        ///Snow from 10 to 15 cm
        ///in 24 hours.
        /// </summary>
        public static string Warning_Rain1 {
            get {
                return ResourceManager.GetString("Warning_Rain1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rain from 41 to 70 mm
        ///in 24 hours
        ///or
        ///Snow from 16 to 30 cm
        ///in 24 hours
        ///or
        ///Snow from 10 to 15 cm
        ///in 12 hours.
        /// </summary>
        public static string Warning_Rain2 {
            get {
                return ResourceManager.GetString("Warning_Rain2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rain above 70 mm
        ///in 24 hours
        ///or
        ///Snow above 30 cm
        ///in 24 hours
        ///or
        ///Snow above 15 cm
        ///in 12 hours.
        /// </summary>
        public static string Warning_Rain3 {
            get {
                return ResourceManager.GetString("Warning_Rain3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rain from 15 to 40 mm
        ///Wind in gusts from 60 to 90 km/h
        ///Hail below 2 cm.
        /// </summary>
        public static string Warning_Storms1 {
            get {
                return ResourceManager.GetString("Warning_Storms1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rain from 41 to 70 mm
        ///Wind in gusts from 91 to 110 km/h
        ///Hail from 2 to 5 cm.
        /// </summary>
        public static string Warning_Storms2 {
            get {
                return ResourceManager.GetString("Warning_Storms2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rain above 70 mm
        ///Wind in gusts over 110 km/h
        ///Hail above 5 cm.
        /// </summary>
        public static string Warning_Storms3 {
            get {
                return ResourceManager.GetString("Warning_Storms3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low risk.
        /// </summary>
        public static string Warning_Tornado1 {
            get {
                return ResourceManager.GetString("Warning_Tornado1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderate risk.
        /// </summary>
        public static string Warning_Tornado2 {
            get {
                return ResourceManager.GetString("Warning_Tornado2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High risk.
        /// </summary>
        public static string Warning_Tornado3 {
            get {
                return ResourceManager.GetString("Warning_Tornado3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In gusts from 70 to 90 km/h.
        /// </summary>
        public static string Warning_Wind1 {
            get {
                return ResourceManager.GetString("Warning_Wind1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In gusts from 91 to 110 km/h.
        /// </summary>
        public static string Warning_Wind2 {
            get {
                return ResourceManager.GetString("Warning_Wind2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In gusts above 100 km/h.
        /// </summary>
        public static string Warning_Wind3 {
            get {
                return ResourceManager.GetString("Warning_Wind3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind.
        /// </summary>
        public static string Wind {
            get {
                return ResourceManager.GetString("Wind", resourceCulture);
            }
        }
    }
}
